### ISSUE TITLE
Ip-adapter issue in Automatic1111

### ISSUE THREAD

**Issue by cgray77** [tencent-ailab/IP-Adapter#117]
> > The error is the following:

> 
> " AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'"
> 
> I have verified that I'm currently running the most current version of torch, and have tried it on multiple checkpoints with the same results.   I tried rolling torch back, but that just borked my entire install. 
> 
> 
> full information: 

> *** Error completing request
> *** Arguments: ('task(5sk5hcig16lthjj)', 'a man, walking down the street', '', [], 20, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001F39B2A44F0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001F39D9213F0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001F39D905180>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001F39D920220>, False, '', 0.5, True, False, '', 'Lerp', False, [], [], False, 0, 0.8, 0, 0.8, 0.5, False, False, 0.5, 8192, -1.0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'CodeFormer', 1, 1, 'None', 1, 1, ['After Upscaling/Before Restore Face'], 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, True, False, False, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', [False], '0', '0', '0.4', None, '0', '0', False, None, False, '0', 'C:\\Users\\Charl\\Documents\\A1111 Web UI Autoinstaller\\stable-diffusion-webui\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, [], [], [], [], '', '', '', '', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, False, False, False, '#000000', False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, None, False, None, None, False, None, None, False, 50, [], 30, '', 4, [], 1, '', '', '', '', 'linear (weight sum)', '10', 'C:\\Users\\Charl\\Documents\\A1111 Web UI Autoinstaller\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-prompt-travel\\img\\ref_ctrlnet', 'Lanczos', 2, 0, 0, 'mp4', 10.0, 0, '', True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, 'linear', 'lerp', 'token', 'random', '30', 'fixed', 1, '8', None, 'Lanczos', 2, 0, 0, 'mp4', 10.0, 0, '', True, False, False) {}
>     Traceback (most recent call last):
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\call_queue.py", line 57, in f
>         res = list(func(*args, **kwargs))
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\call_queue.py", line 36, in f
>         res = func(*args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
>         processed = processing.process_images(p)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\processing.py", line 732, in process_images
>         res = process_images_inner(p)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
>         return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
>         samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 451, in process_sample
>         return process.sample_before_CN_hack(*args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\processing.py", line 1140, in sample
>         samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
>         samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
>         return func()
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
>         samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>         return func(*args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
>         denoised = model(x, sigmas[i] * s_in, **extra_args)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
>         x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
>         eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
>         return self.inner_model.apply_model(*args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
>         setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
>         return self.__orig_func(*args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
>         x_recon = self.model(x_noisy, t, **cond)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
>         out = self.diffusion_model(x, t, context=cc)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 858, in forward_webui
>         raise e
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 855, in forward_webui
>         return forward(*args, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 762, in forward
>         h = module(h, emb, context)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
>         x = layer(x, context)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
>         x = block(x, context=context[i])
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
>         return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
>         return CheckpointFunction.apply(func, len(inputs), *args)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
>         output_tensors = ctx.run_function(*ctx.input_tensors)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
>         x = self.attn2(self.norm2(x), context=context) + x
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>         return forward_call(*input, **kwargs)
>       File "C:\Users\Charl\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 240, in attn_forward_hacked
>         out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0.0, is_causal=False)
>     AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'
>

**Comment by xiaohu2015** [comment]
@cgray77 update torch to 2.0
