### ISSUE TITLE
Face model loading error

### ISSUE THREAD

**Issue by xiaocaijiayou** [tencent-ailab/IP-Adapter#119]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:17<00:00,  2.43s/it]
Traceback (most recent call last):
  File "./inference_ip_adapter_sdxl_plus-face_demo.py", line 32, in <module>
    ip_model = IPAdapterPlusXL(pipe, image_encoder_path, ip_ckpt, device, num_tokens=16)
  File "./ip_adapter/ip_adapter.py", line 53, in __init__
    self.load_ip_adapter()
  File "./ip_adapter/ip_adapter.py", line 91, in load_ip_adapter
    self.image_proj_model.load_state_dict(state_dict["image_proj"])
  File "/root/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1664]).

**Comment by xiaohu2015** [comment]
@xiaocaijiayou you should use vith image encoder https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder

**Comment by xiaocaijiayou** [comment]
Thank you for your help! @xiaohu2015
