### ISSUE TITLE
Error running process

### ISSUE THREAD

**Issue by tuweniy** [tencent-ailab/IP-Adapter#128]
Not working
Concole log error:
ControlNet\ip-adapter-plus-face_sd15.safetensors]
*** Error running process: E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 350, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", line 237, in build_model_by_guess
        raise '[ControlNet Error] Cannot recognize the ControlModel!'
    TypeError: exceptions must derive from BaseException

**Comment by NextDiffusion** [comment]
Same error for me. Any solutions for this?

**Comment by xiaohu2015** [comment]
@NextDiffusion @tuweniy because current version of stable-diffusion-webui don't support safetensors (it needs modify some codes)

**Comment by tuweniy** [comment]
when i rename .safetensors in .pth i got this
Concole log error:
2023-11-04 19:32:34,216 - ControlNet - INFO - Loading model: ip-adapter-plus-face_sd15 [7f7a633a]
*** Error running process: E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 349, in build_control_model
        state_dict = load_state_dict(model_path)
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 20, in load_state_dict
        state_dict = unsafe_torch_load(ckpt_path, map_location=torch.device(location))
      File "E:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "E:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
        magic_number = pickle_module.load(f, **pickle_load_args)
    _pickle.UnpicklingError: unpickling stack underflow

**Comment by guoyouworld** [comment]
Same issue  for me ,Any solutions for this?

**Comment by ameen-roayan** [comment]
Same issue here

**Comment by NextDiffusion** [comment]
Issue has been resolved for me! Try upgrading your ControlNet Extension to the latest version. It should work just fine.

**Comment by zhuchun** [comment]
The key is that your controlnet_model_guess.py file can not recognize your safetensor files, some launchers from bilibili have already included the codes that @xiaohu2015 mentioned, but if you're using cloud services like autodl, you need to modify codes yourself, as they're using the official controlnet.

To be more specific, edit "extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", add these lines to line 137
`    if any('image_proj.' in x for x in state_dict.keys()) and any('ip_adapter.' in x for x in state_dict.keys()):  # safetensor ipadapters
        st_model = {"image_proj": {}, "ip_adapter": {}}
        for key in state_dict.keys():
            if key.startswith("image_proj."):
                st_model["image_proj"][key.replace("image_proj.", "")] = state_dict[key]
            elif key.startswith("ip_adapter."):
                st_model["ip_adapter"][key.replace("ip_adapter.", "")] = state_dict[key]
        # sort keys
        model = {"image_proj": st_model["image_proj"], "ip_adapter": {}}
        sorted_keys = sorted(st_model["ip_adapter"].keys(), key=lambda x: int(x.split(".")[0]))
        for key in sorted_keys:
            model["ip_adapter"][key] = st_model["ip_adapter"][key]
        state_dict = model
        del st_model`

**Comment by Skygabriel** [comment]
@zhuchun 
It wokrs, thank you! Here's the code we need, easy for copy:

https://github.com/Mikubill/sd-webui-controlnet/pull/2241/files
