### ISSUE TITLE
InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models

### ISSUE THREAD

**Issue by nanaj96** [tencent-ailab/IP-Adapter#199]

**Comment by nanaj96** [comment]
how can i fix this issue?

**Comment by xiaohu2015** [comment]
https://github.com/deepinsight/insightface/tree/master/python-package#install

**Comment by cdy1996** [comment]
I have installed InsightFace while installing the ReActor component. However, when using FaceId, it still prompts that it is not installed. When I remove ReActor, FaceId works. I feel like there might be a conflict between these two components.


`
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 527, in load_insight_face
    from insightface.app import FaceAnalysis
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\__init__.py", line 116, in <module>
    from onnx import (
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\checker.py", line 29, in <module>
    import onnx.defs
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\defs\__init__.py", line 22, in <module>
    import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 529, in load_insight_face
    raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')
Exception: IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.
`

**Comment by zephirusgit** [comment]
i find the problem.. 
the folder \ComfyUI\web\extensions\pysssss\CustomScripts
i test in new confyui and the same problem but
i copy it again these folder and solve the problem
some folders, are direct shorcuts, i dont know whi.

**Comment by zephirusgit** [comment]
![bug ipadapter](https://github.com/tencent-ailab/IP-Adapter/assets/20031912/a6e536f1-d0c3-4479-a0c0-820ed72a0f98)

**Comment by nanaj96** [comment]
> ![bug ipadapter](https://private-user-images.githubusercontent.com/20031912/293854914-a6e536f1-d0c3-4479-a0c0-820ed72a0f98.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzY0MjIsIm5iZiI6MTcwNDI3NjEyMiwicGF0aCI6Ii8yMDAzMTkxMi8yOTM4NTQ5MTQtYTZlNTM2ZjEtZDBjMy00NDc5LWEwYzAtODIwZWQ3MmEwZjk4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzY2IxODQ1NDc5NTc3MzYzMmY2ODc5NjgyN2QxNjJkZjQ0YmI0NWI4YTYzMGU5ZjE0MjBhYjA0MGIyOGUxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixV5we_o3dwgs1lOY95BlaSO-24-9CzQFBVqXGAS6PE)


Before installing insightface try to install
gcc, g++, cmake and after that do,
'pip install onnx onnxruntime'
And then do
'pip install insightface'

this is worked for me try this
