### ISSUE TITLE
SDXL Full pretrained model

### ISSUE THREAD

**Issue by gsrujana** [tencent-ailab/IP-Adapter#289]
Hi, I am trying to train SDXL with full CLIP embeddings and want to start with your pretrained weights. I modified "num_tokens" in tutorial_train_sdxl.py. Do you have a pretrained version of ipadapter-sdxl-full? I get dimension mismatch error if I start from your sdxl ipadapter model. Thanks

**Comment by xiaohu2015** [comment]
you shoud use this `image projection model`: https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter/ip_adapter.py#L49

**Comment by gsrujana** [comment]
```
self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MLPProjModel:
        Missing key(s) in state_dict: "proj.0.weight", "proj.0.bias", "proj.2.weight", "proj.2.bias", "proj.3.weight", "proj.3.bias". 
        Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "proj.weight", "proj.bias". 
    self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MLPProjModel:
        Missing key(s) in state_dict: "proj.0.weight", "proj.0.bias", "proj.2.weight", "proj.2.bias", "proj.3.weight", "proj.3.bias". 
        Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "proj.weight", "proj.bias". 
Traceback (most recent call last):
  File "tutorial_train_sdxl.py", line 487, in <module>
    main()    
  File "tutorial_train_sdxl.py", line 377, in main
    ip_adapter = IPAdapter(unet, image_proj_model, adapter_modules, args.pretrained_ip_adapter_path)
  File "tutorial_train_sdxl.py", line 161, in __init__
    self.load_from_checkpoint(ckpt_path)
  File "tutorial_train_sdxl.py", line 178, in load_from_checkpoint
    self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MLPProjModel:
        Missing key(s) in state_dict: "proj.0.weight", "proj.0.bias", "proj.2.weight", "proj.2.bias", "proj.3.weight", "proj.3.bias". 
        Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "proj.weight", "proj.bias". 
```

**Comment by gsrujana** [comment]
I am using your SDXL IP_adapter.bin as pretrained_ip_adapter_path. I changed from ImgProjModel to MLProjModel in tutorial_train_sdxl. Any suggestions @xiaohu2015? Thanks!

**Comment by gsrujana** [comment]
Further, how to train using ip-adapter-plus_sdxl_vit-h.bin as starting point? I am training on clothing data.

**Comment by arnobanu** [comment]
> ```
> self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
>  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
>    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for MLPProjModel:
>        Missing key(s) in state_dict: "proj.0.weight", "proj.0.bias", "proj.2.weight", "proj.2.bias", "proj.3.weight", "proj.3.bias". 
>        Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "proj.weight", "proj.bias". 
>    self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
>  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
>    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for MLPProjModel:
>        Missing key(s) in state_dict: "proj.0.weight", "proj.0.bias", "proj.2.weight", "proj.2.bias", "proj.3.weight", "proj.3.bias". 
>        Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "proj.weight", "proj.bias". 
> Traceback (most recent call last):
>  File "tutorial_train_sdxl.py", line 487, in <module>
>    main()    
>  File "tutorial_train_sdxl.py", line 377, in main
>    ip_adapter = IPAdapter(unet, image_proj_model, adapter_modules, args.pretrained_ip_adapter_path)
>  File "tutorial_train_sdxl.py", line 161, in __init__
>    self.load_from_checkpoint(ckpt_path)
>  File "tutorial_train_sdxl.py", line 178, in load_from_checkpoint
>    self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
>  File "/opt/conda/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
>    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for MLPProjModel:
>        Missing key(s) in state_dict: "proj.0.weight", "proj.0.bias", "proj.2.weight", "proj.2.bias", "proj.3.weight", "proj.3.bias". 
>        Unexpected key(s) in state_dict: "norm.weight", "norm.bias", "proj.weight", "proj.bias". 
> ```

I am having the same issue. Could you find any solution?

**Comment by anubhabPanda** [comment]
Any update on the above?
