### ISSUE TITLE
sd faceid crash

### ISSUE THREAD

**Issue by gushenjie** [tencent-ailab/IP-Adapter#302]
报错信息如下

<img width="735" alt="image" src="https://github.com/tencent-ailab/IP-Adapter/assets/10531802/34adca8b-e8ff-4891-b304-3c70e8ebff07">

*** Error running process: /Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/Users/jackgu/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 969, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 969, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 936, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 831, in face_id_plus
        clip_embed, _ = clip(img, config='clip_h', low_vram=low_vram)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 392, in clip
        clip_encoder[config] = ClipVisionDetector(config, low_vram)
      File "/Users/jackgu/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/__init__.py", line 116, in __init__
        self.model.load_state_dict(sd, strict=False)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1994, in load_state_dict
        raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
    TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

**Comment by xiaohu2015** [comment]
you can make a issue in sd-webui-controlnet repo?
