### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by zachysaur** [tencent-ailab/IP-Adapter#309]
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Crop and Resize', low_vram=True, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 119, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 437, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\processing.py", line 1142, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_lcm.py", line 86, in sample_lcm
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 250, in mm_cfg_forward
        x_out = mm_sd_forward(self, x_in, sigma_in, cond_in, image_cond_in, make_condition_dict) # hook
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 159, in mm_sd_forward
        mm_cn_select(_context)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 121, in mm_cn_select
        elif control.control_model_type == ControlModelType.IPAdapter and control.control_model.image_emb.shape[0] > len(context):
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'PlugableIPAdapter' object has no attribute 'image_emb'. Did you mean: 'get_image_emb'?

**Comment by xiaohu2015** [comment]
can you make a pr at WebUI repo？

**Comment by hwy-202011** [comment]
i have the same isue
