### ISSUE TITLE
 送么error when convert the weights with the following code

### ISSUE THREAD

**Issue by masaisai111** [tencent-ailab/IP-Adapter#332]
Q1：
import torch
ckpt = "IP-Adapter/sd-ip_adapter/checkpoint-6000/model.safetensors"
sd = torch.load(ckpt, map_location="cpu")
#print(sd )
image_proj_sd = {}
ip_sd = {}
for k in sd:
    if k.startswith("unet"):
        pass
    elif k.startswith("image_proj_model"):
        image_proj_sd[k.replace("image_proj_model.", "")] = sd[k]
    elif k.startswith("adapter_modules"):
        ip_sd[k.replace("adapter_modules.", "")] = sd[k]

torch.save({"image_proj": image_proj_sd, "ip_adapter": ip_sd}, "ip_adapter.bin")
Why is there an error：
Traceback (most recent call last):
  File "/home/AAAAduibixiangmu/IP-Adapter/change.py", line 3, in <module>
    sd = torch.load(ckpt, map_location="cpu")
  File "/home/anaconda3/envs/IP-Adapter/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/IP-Adapter/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xd8'.？

**Comment by misshimichka** [comment]
hi @masaisai111, I had similar issue and found the answer [here](https://github.com/tencent-ailab/IP-Adapter/issues/172) maybe this can help you

**Comment by irsLu** [comment]
I have same error, could you solve this problem?
