### ISSUE TITLE
 ImportError: cannot import name 'ValidationInfo' from 'pydantic' 

### ISSUE THREAD

**Issue by hayashilee** [tencent-ailab/IP-Adapter#389]
when i use the faceid models,it generated a normal picture,and it shows the issues:
Error running process: F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "F:\project_soft\sd-webui-aki-v4.8\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1222, in process
        self.controlnet_hack(p)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1207, in controlnet_hack
        self.controlnet_main_entry(p)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 196, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 209, in _cached_call
        return self(*args, **kwargs)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\preprocessor\ip_adapter_auto.py", line 25, in __call__
        return p(*args, **kwargs)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
        result, is_image = self.call_function(
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 749, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 677, in run_model
        self.load_model()
      File "F:\project_soft\sd-webui-aki-v4.8\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 667, in load_model
        from insightface.app import FaceAnalysis
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\insightface\__init__.py", line 18, in <module>
        from . import app
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
        from .mask_renderer import *
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
        import albumentations as A
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\albumentations\__init__.py", line 5, in <module>
        from .augmentations import *
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\albumentations\augmentations\__init__.py", line 1, in <module>
        from .blur.functional import *
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
        from .functional import *
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\albumentations\augmentations\blur\functional.py", line 10, in <module>
        from albumentations.augmentations.geometric.functional import scale
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\albumentations\augmentations\geometric\__init__.py", line 2, in <module>
        from .resize import *
      File "F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\albumentations\augmentations\geometric\resize.py", line 6, in <module>
        from pydantic import Field, ValidationInfo, field_validator
    ImportError: cannot import name 'ValidationInfo' from 'pydantic' (F:\project_soft\sd-webui-aki-v4.8\python\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

**Comment by fu-jianhua** [comment]
I also encountered this problem, have you solved it?
