### ISSUE TITLE
!!! Exception during processing !!! local variable 'face_image' referenced before assignment Traceback (most recent call last):

### ISSUE THREAD

**Issue by Tahsure** [tencent-ailab/IP-Adapter#423]
Queue size: 0
ERROR
CPU
11%
RAM
60%
GPU
5%
VRAM
22%
Temp
59°
HDD
25%
Extra options
IPAdapterBatch

local variable 'face_image' referenced before assignment

# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterBatch
- **Exception Type:** UnboundLocalError
- **Exception Message:** local variable 'face_image' referenced before assignment
## Stack Trace
```
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 825, in apply_ipadapter
    return (work_model, face_image, )

```
## System Information
- **ComfyUI Version:** v0.2.0-2-g00a5d08
- **Arguments:** F:\StabilityMatrix\Packages\ComfyUI\main.py --lowvram --preview-method auto
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 10736893952
  - **VRAM Free:** 9235459840
  - **Torch VRAM Total:** 234881024
  - **Torch VRAM Free:** 23719680

## Logs
```
2024-09-03 20:06:47,718 - root - INFO - Total VRAM 10240 MB, total RAM 32556 MB
2024-09-03 20:06:47,719 - root - INFO - pytorch version: 2.1.2+cu121
2024-09-03 20:06:47,719 - root - INFO - Set vram state to: LOW_VRAM
2024-09-03 20:06:47,719 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
2024-09-03 20:06:48,253 - root - INFO - Using pytorch cross attention
2024-09-03 20:06:48,712 - root - INFO - [Prompt Server] web root: F:\StabilityMatrix\Packages\ComfyUI\web
2024-09-03 20:06:48,713 - root - INFO - Adding extra search path checkpoints F:\StabilityMatrix\Models\StableDiffusion
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path vae F:\StabilityMatrix\Models\VAE
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path loras F:\StabilityMatrix\Models\Lora
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path loras F:\StabilityMatrix\Models\LyCORIS
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path upscale_models F:\StabilityMatrix\Models\ESRGAN
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path upscale_models F:\StabilityMatrix\Models\RealESRGAN
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path upscale_models F:\StabilityMatrix\Models\SwinIR
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path embeddings F:\StabilityMatrix\Models\TextualInversion
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path hypernetworks F:\StabilityMatrix\Models\Hypernetwork
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path controlnet F:\StabilityMatrix\Models\ControlNet
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path controlnet F:\StabilityMatrix\Models\T2IAdapter
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path clip F:\StabilityMatrix\Models\CLIP
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path clip_vision F:\StabilityMatrix\Models\InvokeClipVision
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path diffusers F:\StabilityMatrix\Models\Diffusers
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path gligen F:\StabilityMatrix\Models\GLIGEN
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path vae_approx F:\StabilityMatrix\Models\ApproxVAE
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path ipadapter F:\StabilityMatrix\Models\IpAdapter
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path ipadapter F:\StabilityMatrix\Models\InvokeIpAdapters15
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path ipadapter F:\StabilityMatrix\Models\InvokeIpAdaptersXl
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path prompt_expansion F:\StabilityMatrix\Models\PromptExpansion
2024-09-03 20:06:48,714 - root - INFO - Adding extra search path unet F:\StabilityMatrix\Models\unet
2024-09-03 20:06:49,228 - root - WARNING - Skip F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
2024-09-03 20:06:49,309 - root - INFO - Total VRAM 10240 MB, total RAM 32556 MB
2024-09-03 20:06:49,309 - root - INFO - pytorch version: 2.1.2+cu121
2024-09-03 20:06:49,309 - root - INFO - Set vram state to: LOW_VRAM
2024-09-03 20:06:49,309 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
2024-09-03 20:06:49,792 - numexpr.utils - INFO - Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
2024-09-03 20:06:49,792 - numexpr.utils - INFO - NumExpr defaulting to 16 threads.
2024-09-03 20:06:50,033 - root - WARNING - Traceback (most recent call last):
  File "F:\StabilityMatrix\Packages\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\StabilityMatrix\\Packages\\ComfyUI\\custom_nodes\\Stable-Diffusion-WebUI-TensorRT\\__init__.py'

2024-09-03 20:06:50,033 - root - WARNING - Cannot import F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\Stable-Diffusion-WebUI-TensorRT module for custom nodes: [Errno 2] No such file or directory: 'F:\\StabilityMatrix\\Packages\\ComfyUI\\custom_nodes\\Stable-Diffusion-WebUI-TensorRT\\__init__.py'
2024-09-03 20:06:50,033 - root - INFO - 
Import times for custom nodes:
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\Stable-Diffusion-WebUI-TensorRT
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-MeshMesh
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Loopchain
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-SuperBeasts
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-03 20:06:50,033 - root - INFO -    0.0 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-03 20:06:50,033 - root - INFO -    0.1 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-09-03 20:06:50,033 - root - INFO -    0.1 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-03 20:06:50,033 - root - INFO -    0.1 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-03 20:06:50,033 - root - INFO -    0.2 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-09-03 20:06:50,033 - root - INFO -    0.2 seconds: F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-03 20:06:50,033 - root - INFO - 
2024-09-03 20:06:50,039 - root - INFO - Starting server

2024-09-03 20:06:50,039 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-03 20:06:56,659 - root - INFO - got prompt
2024-09-03 20:06:57,086 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-09-03 20:06:57,087 - root - INFO - model_type EPS
2024-09-03 20:06:57,416 - root - INFO - Using pytorch attention in VAE
2024-09-03 20:06:57,416 - root - INFO - Using pytorch attention in VAE
2024-09-03 20:06:57,736 - root - INFO - Requested to load SD1ClipModel
2024-09-03 20:06:57,737 - root - INFO - Loading 1 new model
2024-09-03 20:06:57,739 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-09-03 20:06:59,949 - root - INFO - Requested to load CLIPVisionModelProjection
2024-09-03 20:06:59,949 - root - INFO - Loading 1 new model
2024-09-03 20:06:59,956 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-09-03 20:07:41,828 - root - ERROR - !!! Exception during processing !!! local variable 'face_image' referenced before assignment
2024-09-03 20:07:41,829 - root - ERROR - Traceback (most recent call last):
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 825, in apply_ipadapter
    return (work_model, face_image, )
UnboundLocalError: local variable 'face_image' referenced before assignment

2024-09-03 20:07:41,830 - root - INFO - Prompt executed in 44.97 seconds
2024-09-03 20:07:44,719 - root - INFO - got prompt
2024-09-03 20:07:45,025 - root - ERROR - !!! Exception during processing !!! local variable 'face_image' referenced before assignment
2024-09-03 20:07:45,026 - root - ERROR - Traceback (most recent call last):
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 825, in apply_ipadapter
    return (work_model, face_image, )
UnboundLocalError: local variable 'face_image' referenced before assignment

2024-09-03 20:07:45,027 - root - INFO - Prompt executed in 0.12 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

![comfy error](https://github.com/user-attachments/assets/1a6df354-a20b-4357-b4e8-a3b8ec293064)

**Comment by Tahsure** [comment]
please help i cant seem to find a similar issue anywhere, I have updated comfyui and my ipadapter plugin as well.

**Comment by Tahsure** [comment]
I just solved the issue. I should have chosen another parameter in the ipadapter weights plugin.
Which is alternate batches instead of full batch. :D

![comfy solved](https://github.com/user-attachments/assets/cbaf20d0-875a-42ec-a572-3b7bc02108ba)
